server:
  port: 0
  
logging:
  level:
    com.example.ChatterPingBotApplication: debug
    
spring:
  cloud:
    stream:
      bindings:
        output: 
          destination: chat
          
chatter:
  ping:
    interval: 2000
    user: ToRonTo