server:
  port: 0
chatter:
  ping:
    user: PB
    message-format: '[${u}] Ping ${c}.'
    interval: 5000
spring:
  cloud:
    stream:
      bindings:
        output:
          destination: chat
logging:
  level:
    com.example.ChatterBotApplication: debug
