resource_types:
- name: kubernetes
  type: docker-image
  source:
    repository: zlabjp/kubernetes-resource
    tag: 1.9
resources:
- name: git
  type: git
  source:
    uri: git@github.com:kdvolder/chatter.git
    private_key: {{rsa_id}}
    branch: k8s
- name: jdk
  type: docker-image
  source:
    repository: openjdk
    tag: 8-jdk
- name: chatter-web-ui-docker
  type: docker-image
  source:
    repository: kdvolder/chatter-web-ui
    username: {{docker_hub_username}}
    password: {{docker_hub_password}}
- name: pkdv
  type: kubernetes
  source:
    server: https://10.194.72.194:8443
    token: {{kube_token}}
    insecure_skip_tls_verify: true
jobs:
- name: build-chatter-web-ui
  plan:
  - aggregate:
    - get: git
      trigger: true
    - get: jdk
  - task: build
    file: git/ci/tasks/build-fat-jar.yml
    params:
      app_name: chatter-web-ui
    image: jdk
  - put: chatter-web-ui-docker
    params:
      build: out
- name: try-kubectl
  plan:
  - put: pkdv
    params:
      kubectl: cluster-info
