resources:
- name: git
  type: git
  source:
    uri: git@github.com:kdvolder/chatter.git
    private_key: {{rsa_id}}
    branch: master
- name: chatter-web-ui-jar
  type: s3
  source:
    bucket: {{s3_bucket}}
    access_key_id: {{s3_accesskey}}
    secret_access_key: {{s3_secretkey}}
    region_name: {{s3_region}}
    regexp: chatter-demo/chatter-web-ui-(.*)\.jar
- name: jdk
  type: docker-image
  source:
    repository: openjdk
    tag: 8-jdk
jobs:
- name: build-chatter-web-ui
  plan:
  - aggregate:
    - get: git
      trigger: true
    - get: jdk
  - task: build
    file: chatter-git/ci/tasks/build-fat-jar.yml
    params:
      app_name: chatter-web-ui
    image: jdk
  - put: chatter-web-ui-jar
    params:
      file: out/*.jar
