resource_types:
- name: helm
  type: docker-image
  source:
    repository: kdvolder/concourse-helm-resource
resources:
- name: git
  type: git
  source:
    uri: git@github.com:kdvolder/chatter.git
    private_key: {{rsa_id}}
    branch: k8s
- name: jdk
  type: docker-image
  source:
    repository: openjdk
    tag: 8-jdk
- name: chatter-web-ui-docker
  type: docker-image
  source:
    repository: harbor.tan.springapps.io/chatter/web-ui
    tag: concourse
    username: {{harbor_username}}
    password: {{harbor_password}}
    ca_certs:
    - domain: harbor.tan.springapps.io:4443
      cert: {{harbor_ca_cert}}
    insecure_registries:
    - harbor.tan.springapps.io
- name: pkdv
  type: helm
  source:
    kube_config: {{kube_config}}
    release: chatter
jobs:
- name: build-chatter-web-ui
  plan:
  - aggregate:
    - get: git
      trigger: true
    - get: jdk
  - task: build
    file: git/ci/tasks/build-fat-jar.yml
    params:
      app_name: chatter-web-ui
    image: jdk
  - put: chatter-web-ui-docker
    params:
      build: out
- name: deploy-chatter-web-ui
  plan:
  - aggregate:
    - get: git
    - get: chatter-web-ui-docker
      passed:
      - build-chatter-web-ui
      trigger: true
  - put: pkdv
    params:
      chart: git/ci/helm/chatter
      recreate_pods: true
