resources:
- name: chatter-git-docker
  type: git
  source:
    uri: git@github.com:kdvolder/chatter.git
    private_key: {{rsa_id}}
    branch: toronto_2017
    paths:
    - ci/docker
- name: chatter-git
  type: git
  source:
    uri: git@github.com:kdvolder/chatter.git
    private_key: {{rsa_id}}
    branch: toronto_2017
- name: docker
  type: docker-image
  source:
    repository: kdvolder/jdk8
    username: {{docker_hub_username}}
    password: {{docker_hub_password}}
- name: chatter-web-ui-jar
  type: s3
  source:
    bucket: {{s3_bucket}}
    access_key_id: {{s3_accesskey}}
    secret_access_key: {{s3_secretkey}}
    region_name: {{s3_region}}
    regexp: chatter-demo/chatter-web-ui-(.*)\.jar
- name: chatter-banner-service-jar
  type: s3
  source:
    bucket: {{s3_bucket}}
    access_key_id: {{s3_accesskey}}
    secret_access_key: {{s3_secretkey}}
    region_name: {{s3_region}}
    regexp: chatter-demo/chatter-banner-service-(.*)\.jar
- name: chatter-command-bot-jar
  type: s3
  source:
    bucket: {{s3_bucket}}
    access_key_id: {{s3_accesskey}}
    secret_access_key: {{s3_secretkey}}
    region_name: {{s3_region}}
    regexp: chatter-demo/chatter-command-bot-(.*)\.jar
- name: chatter-ping-bot-jar
  type: s3
  source:
    bucket: {{s3_bucket}}
    access_key_id: {{s3_accesskey}}
    secret_access_key: {{s3_secretkey}}
    region_name: {{s3_region}}
    regexp: chatter-demo/chatter-ping-bot-(.*)\.jar
- name: cloudfoundry
  type: cf
  source:
    api: {{cf_api}}
    username: {{cf_user}}
    password: {{cf_password}}
    organization: {{cf_org}}
    space: {{cf_space}}
jobs:
- name: build-docker-image
  plan:
  - get: chatter-git-docker
    trigger: true
  - put: docker
    params:
      build: chatter-git-docker/ci/docker
- name: build-chatter-web-ui
  plan:
  - aggregate:
    - get: chatter-git
      trigger: true
    - get: docker
      passed:
      - build-docker-image
  - task: build
    file: chatter-git/ci/tasks/build-fat-jar.yml
    params:
      app_name: chatter-web-ui
    image: docker
  - put: chatter-web-ui-jar
    params:
      file: out/*.jar
- name: deploy-chatter-web-ui
  serial: true
  plan:
  - aggregate:
    - get: chatter-git
      passed:
      - build-chatter-web-ui
    - get: chatter-web-ui-jar
      passed:
      - build-chatter-web-ui
      trigger: true
  - put: cloudfoundry
    params:
      manifest: chatter-git/chatter-web-ui/manifest.yml
      path: chatter-web-ui-jar/*.jar
- name: build-chatter-banner-service
  plan:
  - aggregate:
    - get: chatter-git
      trigger: true
    - get: docker
      passed:
      - build-docker-image
  - task: build
    file: chatter-git/ci/tasks/build-fat-jar.yml
    params:
      app_name: chatter-banner-service
    image: docker
  - put: chatter-banner-service-jar
    params:
      file: out/*.jar
- name: deploy-chatter-banner-service
  serial: true
  plan:
  - aggregate:
    - get: chatter-git
      passed:
      - build-chatter-banner-service
    - get: chatter-banner-service-jar
      passed:
      - build-chatter-banner-service
      trigger: true
  - put: cloudfoundry
    params:
      manifest: chatter-git/chatter-banner-service/manifest.yml
      path: chatter-banner-service-jar/*.jar
- name: build-chatter-command-bot
  plan:
  - aggregate:
    - get: chatter-git
      trigger: true
    - get: docker
      passed:
      - build-docker-image
  - task: build
    file: chatter-git/ci/tasks/build-fat-jar.yml
    params:
      app_name: chatter-command-bot
    image: docker
  - put: chatter-command-bot-jar
    params:
      file: out/*.jar
- name: deploy-chatter-command-bot
  serial: true
  plan:
  - aggregate:
    - get: chatter-git
      passed:
      - build-chatter-command-bot
    - get: chatter-command-bot-jar
      passed:
      - build-chatter-command-bot
      trigger: true
  - put: cloudfoundry
    params:
      manifest: chatter-git/chatter-command-bot/manifest.yml
      path: chatter-command-bot-jar/*.jar
